INSERT INTO MONHOC_KHAC (Khoa, Ma_Nganh, Ma_Mon_Hoc, Ten_Mon_Hoc, Tin_chi_LT, Tin_chi_TH, Loai) VALUES 
('K16', 'MMT', 'NT531', 'Đánh giá hiệu năng hệ thống mạng máy tính', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT532', 'Công nghệ Internet of things hiện đại', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT533', 'Hệ tính toán phân bố', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT536', 'Công nghệ truyền thông đa phương tiện', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT402', 'Công nghệ mạng viễn thông', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT538', 'Giải thuật xử lý song song và phân bố', 2, 1, 'chuyên ngành'),
('K16', 'MMT', 'NT332', 'Xử lí tín hiệu trong truyền thông', 3, 1, 'chuyên đề'),
('K16', 'MMT', 'NT539', 'AI ứng dụng trong mạng và truyền thông', 3, 1, 'chuyên đề'),
('K16', 'MMT', 'NT405', 'Bảo mật Internet', 2, 1, 'chuyên đề'),
('K16', 'MMT', 'NT121', 'Thiết bị mạng và truyền thông đa phương tiện', 2, 1, 'chuyên đề'),
('K16', 'MMT', 'NT210', 'Thương mại điện tử và triển khai ứng dụng', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT333', 'Tính toán lưới', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT334', 'Pháp chứng kỹ thuật số', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT205', 'Tấn công mạng', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT330', 'An toàn mạng không dây và di động', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT207', 'Quản lý rủi ro và an toàn thông tin trong doanh nghiệp', 3, 3, 'tự chọn'),
('K16', 'MMT', 'NT534', 'An toàn mạng máy tính nâng cao', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT535', 'Bảo mật Internet of things', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT103', 'Hệ điều hành Linux', 3, 1, 'tự chọn'),
('K16', 'MMT', 'NT208', 'Lập trình ứng dụng web', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT201', 'Phân tích thiết kế hệ thống Truyền thông và Mạng', 3, 0, 'tự chọn'),
('K16', 'MMT', 'NT209', 'Lập trình hệ thống', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT104', 'Lý thuyết thông tin', 3, 0, 'tự chọn'),
('K16', 'MMT', 'NT109', 'Lập trình ứng dụng mạng', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT303', 'Công nghệ thoại IP', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT331', 'Xây dựng chuẩn chính sách an toàn thông tin trong doanh nghiệp', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT204', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 2, 1, 'tự chọn'),
('K16', 'MMT', 'NT537', 'Truyền thông xã hội và kinh doanh', 3, 0, 'tự chọn'),
('K17', 'MMT', 'NT531', 'Đánh giá hiệu năng hệ thống mạng máy tính', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT532', 'Công nghệ Internet of things hiện đại', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT533', 'Hệ tính toán phân bố', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT536', 'Công nghệ truyền thông đa phương tiện', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT402', 'Công nghệ mạng viễn thông', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT538', 'Giải thuật xử lý song song và phân bố', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT540', 'Mạng không dây thế hệ mới', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT541', 'Công nghệ mạng khả lập trình', 3, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT542', 'Lập trình kịch bản tự động hóa cho quản trị và bảo mật mạng', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT543', 'Tín hiệu và hệ thống thông tin', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT209', 'Lập trình hệ thống', 2, 1, 'chuyên ngành'),
('K17', 'MMT', 'NT210', 'Thương mại điện tử và triển khai ứng dụng', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT334', 'Pháp chứng kỹ thuật số', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT205', 'Tấn công mạng', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT330', 'An toàn mạng không dây và di động', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT207', 'Quản lý rủi ro và an toàn thông tin trong doanh nghiệp', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT534', 'An toàn mạng máy tính nâng cao', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT405', 'Bảo mật Internet', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT208', 'Lập trình ứng dụng web', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT201', 'Phân tích thiết kế hệ thống Truyền thông và Mạng', 3, 0, 'tự chọn'),
('K17', 'MMT', 'NT109', 'Lập trình ứng dụng mạng', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT204', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT121', 'Thiết bị mạng và truyền thông đa phương tiện', 2, 1, 'tự chọn'),
('K17', 'MMT', 'NT332', 'Xử lý tín hiệu trong Truyền thông', 3, 1, 'chuyên đề'),
('K17', 'MMT', 'NT539', 'AI ứng dụng trong mạng và truyền thông', 3, 1, 'chuyên đề'),
('K17', 'MMT', 'NT535', 'Bảo mật Internet of Things', 2, 1, 'chuyên đề'),
('K17', 'MMT', 'NT544', 'Ăng ten và truyền thông vô tuyến', 3, 1, 'chuyên đề'),
('K17', 'MMT', 'NT545', 'Thiết kế hệ thống viễn thông', 2, 1, 'chuyên đề'),
('K17', 'MMT', 'NT546', 'Thiết kế và triển khai mạng tốc độ cao', 2, 1, 'chuyên đề'),
('K18','MMT','NT531','Đánh giá hiệu năng hệ thống',2,1, 'chuyên ngành'),
('K18','MMT','NT532','Công nghệ Internet of things hiện địa',2,1,'chuyên ngành'),
('K18','MMT','NT533','Hệ tính toán phân bố',2,1,'chuyên ngành'),
('K18','MMT','NT536','Công nghệ truyền thông đa phương tiện',2,1,'chuyên ngành'),
('K18','MMT','NT402','Công nghệ mạng viễn thông',2,1,'chuyên ngành'),
('K18','MMT','NT538','Giải thuật xử lí song song và phân bố',2,1,'chuyên ngành'),
('K18','MMT','NT540','Mạng không dây thế hệ mới',2,1,'chuyên ngành'),
('K18','MMT','NT541','Công nghệ mạng khả lập trình',3,1,'chuyên ngành'),
('K18','MMT','NT542','Lập trình kịch bản tự động hóa cho quản trị và bảo mật mạng',2,1,'chuyên ngành'),
('K18','MMT','NT543','Tín hiệu và hệ thống thông tin',2,1,'chuyên ngành'),
('K18','MMT','NT209','Lập trình hệ thống',2,1,'chuyên ngành'),
('K18','MMT','NT210','Thương mại điện tử và triển khai ứng dụng',2,1,'tự chọn'),
('K18','MMT','NT334','Pháp chứng kỹ thuật số',2,1,'tự chọn'),
('K18','MMT','NT205','Tấn công mạng',2,1,'tự chọn'),
('K18','MMT','NT330','An toàn mạng không dây và di động',2,1,'tự chọn'),
('K18','MMT','NT207','Quản lí rủi ro và an toàn thông tin trong doanh nghiệp',3,3,'tự chọn'),
('K18','MMT','NT534','An toàn mạng máy tính nâng cao',2,1,'tự chọn'),
('K18','MMT','NT405','Bảo mật Internet',2,1,'tự chọn'),
('K18','MMT','NT208','Lập trình ứng dụng web',2,1,'tự chọn'),
('K18','MMT','NT201','Phân tích thiết kế hệ thống Truyền thông và Mạng',3,0,'tự chọn'),
('K18','MMT','NT109','Lập trình ứng dụng mạng',2,1,'tự chọn'),
('K18','MMT','NT204','Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập',2,1,'tự chọn'),
('K18','MMT','NT121','Thiết bị mạng và truyền thông đa phương tiện',2,1,'tự chọn'),
('K18','MMT','NT332','Xử lí tín hiệu trong Truyền thông',3,1,'chuyên đề'),
('K18','MMT','NT539','AI ứng dụng trong mạng và truyền thông',3,1,'chuyên đề'),
('K18','MMT','NT535','Bảo mật Internet of Things',2,1,'chuyên ngành'),
('K18','MMT','NT544','Ăng ten và truyền thông vô tuyến',3,1,'chuyên đề'),
('K18','MMT','NT545','Thiết kế hệ thống viễn thông',2,1,'chuyên đề'),
('K18','MMT','NT546','Thiết kế và triển khai mạng tốc độ cao',2,1,'chuyên đề'),
('K19','MMT','NT531','Đánh giá hiệu năng hệ thống',2,1,'chuyên ngành'),
('k19','MMT','NT532','Công nghệ Internet of things hiện địa',2,1,'chuyên ngành'),
('k19','MMT','NT533','Hệ tính toán phân bố',2,1,'chuyên ngành'),
('k19','MMT','NT536','Công nghệ truyền thông đa phương tiện',2,1,'chuyên ngành'),
('k19','MMT','NT402','Công nghệ mạng viễn thông',2,1,'chuyên ngành'),
('k19','MMT','NT538','Giải thuật xử lí song song và phân bố',2,1,'chuyên ngành'),
('k19','MMT','NT540','Mạng không dây thế hệ mới',2,1,'chuyên ngành'),
('k19','MMT','NT542','Lập trình kịch bản tự động hóa cho quản trị và bảo mật mạng',2,1,'chuyên ngành'),
('k19','MMT','NT543','Tín hiệu và hệ thống thông tin',2,1,'chuyên ngành'),
('k19','MMT','NT535','Bảo mật Internet of Things',2,1,'chuyên ngành'),
('k19','MMT','NT545','Thiết kế hệ thống viễn thông',2,1,'chuyên ngành'),
('k19','MMT','NT546','Thiết kế và triển khai mạng tốc độ cao',2,1,'chuyên ngành'),
('k19','MMT','NT209','Lập trình hệ thống',2,1,'chuyên ngành'),
('k19','MMT','NT210','Thương mại điện tử và triển khai ứng dụng',2,1,'tự chọn'),
('k19','MMT','NT334','Pháp chứng kỹ thuật số',2,1,'tự chọn'),
('k19','MMT','NT205','Tấn công mạng',2,1,'tự chọn'),
('k19','MMT','NT330','An toàn mạng không dây và di động',2,1,'tự chọn'),
('k19','MMT','NT207','Quản lí rủi ro và an toàn thông tin trong doanh nghiệp',3,3,'tự chọn'),
('k19','MMT','NT534','An toàn mạng máy tính nâng cao',2,1,'tự chọn'),
('k19','MMT','NT405','Bảo mật Internet',2,1,'tự chọn'),
('k19','MMT','NT208','Lập trình ứng dụng web',2,1,'tự chọn'),
('k19','MMT','NT201','Phân tích thiết kế hệ thống Truyền thông và Mạng',3,0,'tự chọn'),
('k19','MMT','NT109','Lập trình ứng dụng mạng',2,1,'tự chọn'),
('k19','MMT','NT204','Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập',2,1,'tự chọn'),
('k19','MMT','NT121','Thiết bị mạng và truyền thông đa phương tiện',2,1,'tự chọn'),
('k19','MMT','NT332','Xử lí tín hiệu trong Truyền thông',3,1,'chuyên đề'),
('k19','MMT','NT539','AI ứng dụng trong mạng và truyền thông',3,1,'chuyên đề'),
('k19','MMT','NT541','Công nghệ mạng khả lập trình',3,1,'chuyên đề'),
('k19','MMT','NT544','Ăng ten và truyền thông vô tuyến',3,1,'chuyên đề'),
('k19','MMT','NT548','Công nghệ DevOps và ứng dụng',3,1,'chuyên đề'),
('K16', 'ATTT', 'NT131', 'Hệ thống nhúng Mạng không dây', 3, 1,'chuyên đề'),
('K16', 'ATTT', 'NT208', 'Lập trình ứng dụng Web', 2, 1, 'chuyên đề'),
('K16', 'ATTT', 'NT205', 'Tấn công mạng', 2, 1, 'chuyên đề'),
('K16', 'ATTT', 'NT532', 'Công nghệ Internet of Things hiện đại', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT535', 'Bảo mật Internet of things', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT211', 'An ninh nhân sự, định danh và chứng thực', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT212', 'An toàn dữ liệu, khôi phục thông tin sau sự cố', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT534', 'An toàn mạng máy tính nâng cao', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT133', 'An toàn kiến trúc hệ thống', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT521', 'Lập trình an toàn và khai thác lỗ hổng phần mềm', 3, 1, 'tự chọn'),
('K16', 'ATTT', 'NT522', 'Phương pháp học máy trong an toàn thông tin', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT523', 'An toàn thông tin trong kỷ nguyên máy tính lượng tử', 2, 1, 'tự chọn'),
('K16', 'ATTT', 'NT204', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 2, 1, 'chuyên ngành'),
('K16', 'ATTT', 'NT330', 'An toàn mạng không dây và di động', 2, 1, 'chuyên ngành'),
('K16', 'ATTT', 'NT207', 'Quản lý rủi ro và an toàn thông tin trong doanh nghiệp', 2, 1, 'chuyên ngành'),
('K16', 'ATTT', 'NT137', 'Kỹ thuật phân tích mã độc', 2, 1, 'chuyên ngành'),
('K16', 'ATTT', 'NT213', 'Bảo mật web và ứng dụng', 2, 1, 'chuyên ngành'),
('K16', 'ATTT', 'NT334', 'Pháp chứng kỹ thuật số', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT204', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT330', 'An toàn mạng không dây và di động', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT207', 'Quản lý rủi ro và an toàn thông tin trong doanh nghiệp', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT137', 'Kỹ thuật phân tích mã độc', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT213', 'Bảo mật web và ứng dụng', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT334', 'Pháp chứng kỹ thuật số', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT535', 'Bảo mật Internet of things', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT211', 'An ninh nhân sự, định danh và chứng thực', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT212', 'An toàn dữ liệu, khôi phục thông tin sau sự cố', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT534', 'An toàn mạng máy tính nâng cao', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT133', 'An toàn kiến trúc hệ thống', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT523', 'An toàn thông tin trong kỷ nguyên Máy tính lượng tử', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT205', 'Tấn công mạng', 2, 1, 'chuyên ngành'),
('K17', 'ATTT', 'NT541', 'Công nghệ mạng khả lập trình', 3, 1, 'chuyên đề'),
('K17', 'ATTT', 'NT533', 'Hệ tính toán phân bố', 2, 1, 'chuyên đề'),
('K17', 'ATTT', 'NT522', 'Phương pháp học máy trong an toàn thông tin', 2, 1, 'chuyên đề'),
('K18','ATTT','NT204','Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập',2,1,'chuyên ngành'),
('K18','ATTT','NT330','An toàn mạng không dây và di động',2,1,'chuyên ngành'),
('K18','ATTT','NT207','Quản lý rủi ro và an toàn thông tin trong doanh nghiệp',2,1,'chuyên ngành'),
('K18','ATTT','NT137','Kỹ thuật phân tích mã độc',2,1,'chuyên ngành'),
('K18','ATTT','NT213','Bảo mật web và ứng dụng',2,1,'chuyên ngành'),
('K18','ATTT','NT334','Pháp chứng kỹ thuật số',2,1,'chuyên ngành'),
('K18','ATTT','NT535','Bảo mật Internet of things',2,1,'chuyên ngành'),
('K18','ATTT','NT211','An ninh nhân sự, định danh và chứng thực',3,1,'chuyên ngành'),
('K18','ATTT','NT212','An toàn dữ liệu, khôi phục thông tin sau sự cố',2,1,'chuyên ngành'),
('K18','ATTT','NT534','An toàn mạng máy tính nâng cao',2,1,'chuyên ngành'),
('K18','ATTT','NT133','An toàn kiến trúc hệ thống',2,1,'chuyên ngành'),
('K18','ATTT','NT523','An toàn thông tin trong kỷ nguyên Máy tính lượng tử',2,1,'chuyên ngành'),
('K18','ATTT','NT205','Tấn công mạng',2,1,'chuyên ngành'),
('K18','ATTT','NT547','Blockchain: nền tảng, ứng dụng và bảo mật',2,1,'chuyên ngành'),
('K18','ATTT','NT118','Phát triển ứng dụng trên thiết bị di động',2,1,'chuyên ngành'),
('K18','ATTT','NT541','Công nghệ mạng khả lập trình',3,1,'chuyên đề'),
('K18','ATTT','NT533','Hệ tính toán phân bố',2,1,'chuyên đề'),
('K18','ATTT','NT522','Phương pháp học máy trong an toàn thông tin',2,1,'chuyên đề'),
('K19','ATTT','NT204','Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập',2,1,'chuyên ngành'),
('K19','ATTT','NT330','An toàn mạng không dây và di động',2,1,'chuyên ngành'),
('K19','ATTT','NT207','Quản lý rủi ro và an toàn thông tin trong doanh nghiệp',2,1,'chuyên ngành'),
('K19','ATTT','NT137','Kỹ thuật phân tích mã độc',2,1,'chuyên ngành'),
('K19','ATTT','NT213','Bảo mật web và ứng dụng',2,1,'chuyên ngành'),
('K19','ATTT','NT334','Pháp chứng kỹ thuật số',2,1,'chuyên ngành'),
('K19','ATTT','NT535','Bảo mật Internet of things',2,1,'chuyên ngành'),
('K19','ATTT','NT211','An ninh nhân sự, định danh và chứng thực',3,1,'chuyên ngành'),
('K19','ATTT','NT212','An toàn dữ liệu, khôi phục thông tin sau sự cố',2,1,'chuyên ngành'),
('K19','ATTT','NT534','An toàn mạng máy tính nâng cao',2,1,'chuyên ngành'),
('K19','ATTT','NT133','An toàn kiến trúc hệ thống',2,1,'chuyên ngành'),
('K19','ATTT','NT523','An toàn thông tin trong kỷ nguyên Máy tính lượng tử',2,1,'chuyên ngành'),
('K19','ATTT','NT205','Tấn công mạng',2,1,'chuyên ngành'),
('K19','ATTT','NT547','Blockchain: nền tảng, ứng dụng và bảo mật',2,1,'chuyên ngành'),
('K19','ATTT','NT118','Phát triển ứng dụng trên thiết bị di động',2,1,'chuyên ngành'),
('K19','ATTT','NT522','Phương pháp học máy trong an toàn thông tin',2,1,'chuyên ngành'),
('K19','ATTT','NT541','Công nghệ mạng khả lập trình',3,1,'chuyên đề'),
('K19','ATTT','NT548','Công nghệ DevOps và ứng dụng',3,1,'chuyên đề');